### ISSUE TITLE
Created file is hidden

### ISSUE THREAD

**Issue by bkqtnte10** [bradyt/cone#11]
The created file in /storage/emulated/0/Documents/cone is created as hidden file.

Can it be made regular or mentioned that it is hidden in the welcome screen?

Thank you for this app

**Comment by bradyt** [comment]
@bkqtnte10 Thank you for the issue, and your appreciation.

I hope this is considered fixed in `v0.2.0`, which is waiting to be merged at https://gitlab.com/fdroid/fdroiddata/merge_requests/5050, and then I think less than a week from then to appear on F-Droid repo.

The behavior in that pending release, is that users will be prompted to pick a `.txt` ledger file.

I will ping the thread when I see it on F-Droid repo.

Please note, this version `v0.2.0` requires Android version >= 4.4, KitKat, (API 19). This bump from 4.1, JellyBean, (API 16), apparently would exclude about 3.2% of existing Android devices. I would like to cover this version at some point. Anyone, please file an issue if this is urgent.

- https://developer.android.com/about/dashboards/index.html
- https://en.wikipedia.org/wiki/Android_version_history

**Comment by bradyt** [comment]
👋, `v0.2.0` is now on F-Droid and Google Play. I assume this fixes current issue. Or let me know if not.
