### ISSUE TITLE
Allow opening any file as text

### ISSUE THREAD

**Issue by daraul** [bradyt/cone#17]
I'm not sure what file types cone can open, but I know my `master.ledger` file isn't compatible, but the same file as `master.txt` is.

Not a huge issue, but a nice to have :)

**Comment by bradyt** [comment]
Yes that would simplify things, since many users will expect this to work with `.ledger`, `.dat`, `.hledger`, `.journal`, etc.

Currently we use `intent.setType("text/plain");` in [`MainActivity.java`](https://github.com/bradyt/cone/blob/master/android/app/src/main/java/info/tangential/cone/MainActivity.java), so for whatever reason, I guess Android does not think your file is plain text.

I would like to prevent someone from accidentally picking their important photos or pdfs, for example, and ruining it by appending a plain text ledger transaction. I'm not sure yet a good way to do this. Potentially, we can loosen the intent type to `"*/*", or add `"application/octet-stream"`, the latter being what I think Android sees your `master.ledger` as. Should we have some sort of heuristic that scans the file to make sure it looks like plain text? Or for a quick fix, just show the user the first characters of the file, and ask them if they're sure this is a text file. I've seen some Android text editors that let you toggle a setting, to not limit to `"text/plain"`. But I'd really like to avoid just letting users corrupt a file.

**Comment by daraul** [comment]
Changing the intent type to `application/octet-stream` sounds like a good idea, but I can't be sure.

**Comment by bradyt** [comment]
But would that leave files that are `application/octet-stream` but not actually plain text open to corruption?

**Comment by daraul** [comment]
I had no idea, to be honest, but I did some looking and it seems like `application/octet-stream` is used for binary files. 

See here: https://kb.iu.edu/d/agtj

I think that'd make it unsuitable for cone's purposes.

**Comment by alerque** [comment]
I don't think it really matters what other file types might fall under that classification, if Android classifies `*.ledger` as `application/octet-stream` just based on the filename, then that's what Cone should support. The issues of "leaving other files open to corruption" is not really relevant, that would apply to txt files too. Add a heuristic check after the file is selected to make sure it contains only Unicode text. If not throw and error and make the user pick another filename, otherwise use it.

**Comment by Anachron** [comment]
I was quite confused today when I wanted to initialize cone because it wouldn't let me choose `.dat` files. It took me a while to figure out it only supports `.txt` files. 

Maybe until this feature is done we can at least give the users a little hint?

**Comment by daraul** [comment]
I think the user should be responsible for what files they open in cone. Perhaps put a notice when opening the file that if it's anything but plain text, it might be corrupted?

**Comment by Anachron** [comment]
Uhm what? I was talking about not being able to choose `.dat` files which confused me. I never said we should prevent users from opening files other than text files. Please read again.

**Comment by bradyt** [comment]
In an effort to simplify the discussion, I've made the comment a separate issue.

**Comment by bradyt** [comment]
I think I have some ideas on why we can open up the options. The important thing is if someone breaks their file, we need to quickly add some heuristics. I will wait until I have a better regex working for the file, we could quickly swap that in as part of heuristics if issues arise. Additionally, I will try to add the mime type to features of file listed via the info button next to the selected file button.

I will probably start with adding `application/octet-stream`, as I hope that covers how Android treats, `.dat`, `.journal`, `.ledger`, etc. This might prevent a casual user from selecting, `wedding-photo.png` or `birth-certificate.pdf`.

Just adding the mime type, and having those other features in the ready, will hopefully contribute to improving the app but keeping the UI still very simple, and not too risky. I think the above is a good and simple compromise.

**Comment by daraul** [comment]
My comment was more in reply to @alerque's comment before yours, @Anachron

**Comment by daraul** [comment]
> I will wait until I have a better regex working for the file

What do you mean by this exactly, @bradyt? I can help with the regex if you need

**Comment by bradyt** [comment]
> What do you mean by this exactly, @bradyt? I can help with the regex if you need

I'd like to make a library cone_lib, that takes a file as a Stream, and returns an object that has an API to get a Stream of accounts, Stream of payees, and Stream of transaction objects. This way, the home screen could be a reverse order view of the transactions in the file.

**Comment by daraul** [comment]
Brilliant idea! Off topic question: do you test this application? How?

**Comment by bradyt** [comment]
> Ad-hoc parsing for the transactions I haven't worked out yet.

Ah, perhaps not ideal, but I think I have a multiline regex that grabs transactions whole, then it should be straightforward from here.

> Off topic question: do you test this application? How?

I'm not sure I understand. Can you give an example of what you mean by test?

**Comment by bradyt** [comment]
@daraul Perhaps we should consider that some may be subscribed to this thread for a specific reason. There are options for chat. Or feel free to open a well written issue with the question, or even if you're not sure what chat options we have.

**Comment by bradyt** [comment]
> Off topic question: do you test this application? How?

Another response suggested to me is:

> I would say "Yes, I test [cone]. Do you have evidence to the contrary? Is there a kind of testing I don't do, that you want?"

**Comment by bradyt** [comment]
I've added the mimetype `application/octet-stream`. On my device, I'm seeing .ledger, .dat, .journal, available in the document picker.

It's already on Google Play. There is an open merge request at F-Droid, https://gitlab.com/fdroid/fdroiddata/merge_requests/5301.

**Comment by bradyt** [comment]
Closing issue, as I suspect the main ideas of the original issue will not resurface after `v0.2.4+12`.

There are tangential ideas raised here, and they are not discarded. I have added a few notes to the wiki, as a reminder of ideas about heuristics, tests, UI, etc. If you think they are more pressing than to simply be noted on the wiki, please feel free to file an issue, or if you think this issue should be reopened, that's fine.

Of course, feel free to restructure the wiki.
