### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by e18r** [bradyt/cone#7]
I'm really grateful for this small app, so I'd like to contribute to its development. I have experience with Java, although I'm not very familiar with Android development. But I'm always eager to learn.

So I thought my first contribution could be to create a "How to Contribute" section in the readme. What do you think, @bradyt? If you agree, just reply with a quick explanation on how to compile. I suppose you have to run `gradle build` and a few other steps? I'll create a PR as soon as I'm able to do it myself.

**Comment by bradyt** [comment]
Hello @e18r 👋

> I'm really grateful for this small app, so I'd like to contribute to its development. I have experience with Java, although I'm not very familiar with Android development. But I'm always eager to learn.
> 

Similar for me. I have written very little Java ever, and I'm not familiar with Android development. I've been wanting an app like this for some time, and for some reason finally took a try with the Flutter framework. It uses the Dart programming language, so your experience with Java may help, as Dart borrows from many places, including Java.

Speaking of Java, I was trying to add an option for users to choose Dropbox for ledger storage. I wrote up an issue at https://github.com/bradyt/cone/issues/8, where I detail what seems to be the two ways we should choose from. Option 1 includes writing some Java. Not sure if you would have an easier time at it than I. I have a repo at `cone_prototypes`, where I try to implement features in a minimal app.

> So I thought my first contribution could be to create a "How to Contribute" section in the readme. What do you think, @bradyt? If you agree, just reply with a quick explanation on how to compile. I suppose you have to run `gradle build` and a few other steps? I'll create a PR as soon as I'm able to do it myself.

As I mention above, this project uses the Flutter framework. I don't know much about how to use `gradle build` within this workflow, but I mostly do things like `flutter build apk`, or `flutter run`.

As for "How to Contribute", I have a tendency to put documentation in the Github wikis, https://github.com/bradyt/cone/wiki/SETUP. That way I don't really have to be concerned with committing messy drafts of documentation to the app repo. I guess anyone can edit the wiki, or clone it, but I don't think Github offers a way for others to push to it.

If that location is okay with you, great! If you think at least the app repos README should point out the wiki, I would agree. I think the F-Droid repo points to this repo, but users may not look farther than the directory and README, since not all Github projects even use the wiki feature.

If you feel the app repo should really have a "how to contribute", I am open to discussing that.

**Comment by e18r** [comment]
@bradyt I'm gonna check out the issue you mention and the wiki. I might just add the link to the wiki in the description, if you agree. Thanks again for this app!

**Comment by bradyt** [comment]
Great! I tried inserting the link next to the description. Let us know if all is in order.

**Comment by bradyt** [comment]
@e18r I feel the project is maturing, as location is now somewhat configurable. I'd like to improve the documentation, including what you described above. Did you still have ideas you want to share on how to improve README or some contributing notes? Otherwise I will probably start drafting this up.

**Comment by e18r** [comment]
Hi @bradyt, thank you so much for thinking about me. At the moment I'm unable to contribute, so please go ahead. Let me thank you again for your wonderful little app - it's become my main ledger app and I use it every day. Do you receive tips in crypto?

**Comment by bradyt** [comment]
Okay, I removed the link to the wiki from the description, and added brief notes to the README, on how to run the app.

I appreciate the question about tips. I've added digital wallet addresses to the README. Let me know if more options should be there.

I realize the contributing notes are brief. At least hopefully there won't be a surprise to those interested, about the use of a framework. I'll close this issue now if noone else objects. Let me know if I missed an aspect of the issue that's important, or feel free to file a new issue.
